version: "3"

# Different container for db and backend and Linking it with links
services:
  pubg-server-1:
    build: .
    ports:
      - 3000
    links:
      - mongo
  pubg-server-2:
    build: .
    ports:
      - 3000
    links:
      - mongo
  pubg-server-3:
    build: .
    ports:
      - 3000
    links:
      - mongo
  load-balancer:
    build: nginx/
    ports:
      - 80:80
    links:
      - pubg-server-1
      - pubg-server-2
      - pubg-server-3
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  # pubg-nepal:
  #   container_name: pubg-nepal-backend
  #   build: ./
  #   command: npm run dev
  #   working_dir: /usr/src/pubgNepalPractice
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   volumes:
  #     - ./:/usr/src/pubgNepalPractice
  #   links:
  #     - mongo
